AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template to create a virtual private cloud.
Resources:
  TESTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: test-vpc

  TESTINTERNETGATEWAY:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: test-igw

  ATTACHIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
         Ref: TESTVPC
      InternetGatewayId:
         Ref: TESTINTERNETGATEWAY

  PUBLICSUBNET:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: TESTVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: public-subnet


  PRIVATESUBNET:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: TESTVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: private-subnet 

  PUBLICROUTETABLE:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: TESTVPC
      Tags:
      - Key: Name
        Value: public-rt           

  PRIVATEROUTETABLE:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: TESTVPC
      Tags:
      - Key: Name
        Value: private-rt

  ASSOCIATEPUBRTWITHPUBLICSUBNET:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PUBLICSUBNET
      RouteTableId:
        Ref: PUBLICROUTETABLE          

  ASSOCIATEPVTRTWITHPRIVATESUBNET:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PRIVATESUBNET
      RouteTableId:
        Ref: PRIVATEROUTETABLE 

  ADDROUTE:
    Type: AWS::EC2::Route
    DependsOn: ATTACHIGW
    Properties:
       RouteTableId:
         Ref: PUBLICROUTETABLE
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: TESTINTERNETGATEWAY

      

       
